stages:
  - build
  - unit-test
  - build-image

build:
  stage: build
  image: golang:latest
  before_script:
    - cd $GOPATH/src
    - mkdir -p gitlab.com/$CI_PROJECT_NAMESPACE
    - cd gitlab.com/$CI_PROJECT_NAMESPACE
    - ln -s $CI_PROJECT_DIR
    - cd $CI_PROJECT_NAME
  script:
    - cd $CI_PROJECT_DIR
    - go mod tidy 
    - go build -o main

unit-test:
  image: golang:latest
  stage: unit-test
  script:
  - go test -v .

build-image:
    stage: build-image
    image: docker:20.10.10
    services:
        - docker:20.10.10-dind     
    script:
        - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
        - docker build -t $CI_REGISTRY_IMAGE .
        - docker push $CI_REGISTRY_IMAGE